/**
 * Seed script — 3 demo personas + their policies.
 *
 * Idempotent: uses onConflictDoNothing() so re-running is safe.
 *
 * Usage (recommended — tsx auto-loads .env.local):
 *   npx tsx --env-file=.env.local src/lib/db/seed.ts
 *
 * Alternative (if tsx >= 4.x):
 *   DATABASE_URL="postgresql://..." npx tsx src/lib/db/seed.ts
 *
 * Requires: npm install -D dotenv tsx  (if not already present)
 */

import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';

import * as schema from './schema';
import type { NewPersona, NewPolicy } from './schema';

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error('❌  DATABASE_URL is not set. Add it to .env.local and retry.');
  process.exit(1);
}

const client = postgres(connectionString, { prepare: false });
const db = drizzle(client, { schema });

// ---------------------------------------------------------------------------
// Seed data — mirrors prototyp/data.js
// ---------------------------------------------------------------------------

const PERSONAS: NewPersona[] = [
  {
    id: 'leon',
    name: 'Leon',
    full_name: 'Leon Brandt',
    initials: 'LB',
    tenure: 'Kunde seit 2022',
  },
  {
    id: 'robert',
    name: 'Robert',
    full_name: 'Robert Hofmann',
    initials: 'RH',
    tenure: 'Kunde seit 2019',
  },
  {
    id: 'julia',
    name: 'Julia',
    full_name: 'Julia Sander',
    initials: 'JS',
    tenure: 'Kundin seit 2025',
  },
];

// Policies keyed by persona_id; UUIDs are generated by the DB (defaultRandom())
const POLICIES: Omit<NewPolicy, 'id'>[] = [
  {
    persona_id: 'leon',
    living_area_m2: 72,
    sum_insured: 65000,
    address: 'Lindenstraße 14 · Mannheim',
    policy_no: 'ADV-HR-2024-10293',
    active: true,
  },
  {
    persona_id: 'robert',
    living_area_m2: 118,
    sum_insured: 95000,
    address: 'Am Stadtpark 7 · Heidelberg',
    policy_no: 'ADV-HR-2021-44817',
    active: true,
  },
  {
    persona_id: 'julia',
    living_area_m2: 54,
    sum_insured: 48000,
    address: 'Kerschensteinerweg 3 · Mannheim',
    policy_no: 'ADV-HR-2025-50922',
    active: true,
  },
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function seed() {
  console.log('🌱  Starting seed…\n');

  // --- Personas ---
  for (const persona of PERSONAS) {
    const result = await db
      .insert(schema.personas)
      .values(persona)
      .onConflictDoNothing({ target: schema.personas.id })
      .returning({ id: schema.personas.id });

    if (result.length > 0) {
      console.log(`  ✅  Persona inserted: ${persona.id} (${persona.full_name})`);
    } else {
      console.log(`  ⏭️   Persona skipped (already exists): ${persona.id}`);
    }
  }

  console.log('');

  // --- Policies ---
  for (const policy of POLICIES) {
    const result = await db
      .insert(schema.policies)
      .values(policy)
      .onConflictDoNothing({ target: schema.policies.policy_no })
      .returning({
        id: schema.policies.id,
        policy_no: schema.policies.policy_no,
      });

    if (result.length > 0) {
      console.log(
        `  ✅  Policy inserted: ${policy.policy_no} → persona ${policy.persona_id}`,
      );
    } else {
      console.log(
        `  ⏭️   Policy skipped (already exists): ${policy.policy_no}`,
      );
    }
  }

  console.log('\n✅  Seed complete.\n');
  await client.end();
}

seed().catch((err) => {
  console.error('❌  Seed failed:', err);
  process.exit(1);
});
